/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import common.Config;
import common.Generator;

/**
 *
 * @author sing1
 */
public class FileNameOutputDialog extends javax.swing.JDialog {
    private String fileNameOutput;
    private boolean isOK = false;
    private HashMap<String, String[]> listData = new HashMap<String, String[]>();

    public String getFileNameOutput() {
        return fileNameOutput;
    }

    public boolean isOK() {
        return isOK;
    }

    /**
     * Creates new form OutputFileNameDialog
     */
    public FileNameOutputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setHotKeys();
        loadOptions();
        try {
            loadData();
            reset();
            this.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot load data", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    private void setHotKeys() {
        this.getRootPane().setDefaultButton(btnOK);
    }

    private void loadOptions() {
        this.cbbValue.setModel(new DefaultComboBoxModel<String>(new String[]{"from_struct", "from_db", "from_generator", "from_default_values"}));
    }

    private void loadData() throws IOException {
        String[] fromDB = Config.getQueryFile().keySet().toArray(String[]::new);
        String[] fromGenerator = Arrays.stream(Generator.Type.values()).map(Enum::name).toArray(String[]::new);
        String[] fromDefaultValues = Config.getValueFile().keySet().toArray(String[]::new);
        this.listData.put("from_struct", new String[]{});
        this.listData.put("from_db", fromDB);
        this.listData.put("from_generator", fromGenerator);
        this.listData.put("from_default_values", fromDefaultValues);
    }

    private void loadDataForOption(String option) {
        String[] data = listData.get(option);
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<String>(data);
        model.insertElementAt("none", 0);
        this.cbbDetailValue.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbValue = new javax.swing.JComboBox<>();
        cbbDetailValue = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPreview = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("File name output");
        setIconImage(((MainForm) this.getParent()).getIconImage());
        setResizable(false);

        cbbValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbValueActionPerformed(evt);
            }
        });

        txtPreview.setEditable(false);
        txtPreview.setColumns(20);
        txtPreview.setRows(1);
        txtPreview.setFocusable(false);
        jScrollPane1.setViewportView(txtPreview);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Preview:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Value:");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbbValue, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbDetailValue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtValue)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbDetailValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(btnOK)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void reset() {
        this.txtPreview.setText("");
        this.txtValue.setText("");
        this.cbbDetailValue.setEnabled(false);
        this.cbbDetailValue.setFocusable(false);
        this.cbbValue.setSelectedIndex(0);
    }

    private void cbbValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbValueActionPerformed
        String option = this.cbbValue.getSelectedItem().toString();
        switch(option) {
            case "from_struct":
                this.txtValue.setEnabled(true);
                this.txtValue.setFocusable(true);
                this.cbbDetailValue.setEnabled(false);
                this.cbbDetailValue.setFocusable(false);
                break;
            default:
                this.txtValue.setEnabled(false);
                this.txtValue.setFocusable(false);
                this.cbbDetailValue.setEnabled(true);
                this.cbbDetailValue.setFocusable(true);
        }
        loadDataForOption(option);
        this.cbbDetailValue.setSelectedIndex(0);
        this.txtValue.setText("");
    }//GEN-LAST:event_cbbValueActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.txtPreview.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String result = this.txtPreview.getText();
        String option = this.cbbValue.getSelectedItem().toString();
        String input = this.txtValue.getText();
        String detailOption = this.cbbDetailValue.getItemCount() > 1 ? this.cbbDetailValue.getSelectedItem().toString() : "";
        if (option.equals("from_struct") && input.length() < 1) {
            JOptionPane.showMessageDialog(this, "Value is not empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        };
        if (input.length() > 0 && !input.matches("^[^~)('!*<>:;,?\\\"*|\\\\/]+$")) {
            JOptionPane.showMessageDialog(this, "A file name cannot contain any of the following characters:\n"
                    + "~ ) ( ' ! * < > : ; , ? \" | \\ /", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ((option.equals("from_db") || option.equals("from_generator") || option.equals("from_default_values")) && this.cbbDetailValue.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(this, "Please choose detail option", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch(option) {
            case "from_struct":
                result += input;
                break;
            case "from_db":
                result += "@{" + detailOption + "}";
                break;
            case "from_generator":
                result += "#{" + detailOption + "}";
                break;
            case "from_default_values":
                result += "*{" + detailOption + "}";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Option is not valid", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        this.txtPreview.setText(result);
        this.cbbValue.setSelectedIndex(0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String name = this.txtPreview.getText().trim();
        if (name == null || name.isBlank()) {
            JOptionPane.showMessageDialog(this, "Value of preview is not empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.fileNameOutput = name;
        this.isOK = true;
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileNameOutputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileNameOutputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileNameOutputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileNameOutputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileNameOutputDialog dialog = new FileNameOutputDialog(new MainForm(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbbDetailValue;
    private javax.swing.JComboBox<String> cbbValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPreview;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
