/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import utils.Config;

/**
 *
 * @author ASUS RG
 */
public class QueriesDialog extends javax.swing.JDialog {

    /**
     * Creates new form QueriesDialog
     */
    public QueriesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            loadQueries();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Cannot load queries", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        resetForm();
    }

    private void resetForm() {
        this.txtKey.setText("");
        this.txtKey.setEditable(true);
        this.txtKey.setFocusable(true);
        this.txtQuery.setText("");
        this.tblQueries.clearSelection();
        this.btnAddQuery.setEnabled(true);
        this.btnUpdateQuery.setEnabled(false);
        this.btnDeleteQuery.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQueries = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        btnAddQuery = new javax.swing.JButton();
        btnUpdateQuery = new javax.swing.JButton();
        btnDeleteQuery = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuery = new javax.swing.JTextArea();
        btnClearText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Queries");
        setMinimumSize(new java.awt.Dimension(800, 600));

        tblQueries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key", "Query"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQueries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQueriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQueries);
        if (tblQueries.getColumnModel().getColumnCount() > 0) {
            tblQueries.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblQueries.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Key:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Query:");

        txtKey.setToolTipText("Enter a key");

        btnAddQuery.setText("Add");
        btnAddQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQueryActionPerformed(evt);
            }
        });

        btnUpdateQuery.setText("Update");
        btnUpdateQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQueryActionPerformed(evt);
            }
        });

        btnDeleteQuery.setText("Delete");
        btnDeleteQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteQueryActionPerformed(evt);
            }
        });

        txtQuery.setColumns(20);
        txtQuery.setRows(5);
        txtQuery.setToolTipText("Enter a query");
        jScrollPane2.setViewportView(txtQuery);

        btnClearText.setText("Clear text");
        btnClearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKey)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnClearText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdateQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddQuery)
                    .addComponent(btnUpdateQuery)
                    .addComponent(btnDeleteQuery)
                    .addComponent(btnClearText))
                .addGap(17, 17, 17))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblQueriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQueriesMouseClicked
        String key = tblQueries.getValueAt(tblQueries.getSelectedRow(), 0).toString();
        String query = tblQueries.getValueAt(tblQueries.getSelectedRow(), 1).toString();
        this.txtKey.setText(key);
        this.txtQuery.setText(query);
        this.txtKey.setEditable(false);
        this.txtKey.setFocusable(false);
        this.btnAddQuery.setEnabled(false);
        this.btnUpdateQuery.setEnabled(true);
        this.btnDeleteQuery.setEnabled(true);
    }//GEN-LAST:event_tblQueriesMouseClicked

    private void btnAddQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQueryActionPerformed
        String key = txtKey.getText().trim();
        String query = txtQuery.getText().trim().replaceAll("\\s+", " ");
        
        if(key.isBlank() || query.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill all!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!key.matches("\\w+")) {
            JOptionPane.showMessageDialog(this, "Key must be contain only letters, numbers and underscore!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (Config.getQueries().containsKey(key)) {
                JOptionPane.showMessageDialog(this, "This key already exists!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Config.setQueries(new HashMap<String, String>() {{
                put(key, query);
            }});

            DefaultTableModel model = (DefaultTableModel) this.tblQueries.getModel();
            model.addRow(new Object[]{key, query});

            resetForm();

            JOptionPane.showMessageDialog(this, "Query added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error while adding query!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddQueryActionPerformed

    private void btnUpdateQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQueryActionPerformed
        if (this.tblQueries.getSelectedRowCount() > 1) {
            JOptionPane.showMessageDialog(this, "Please only select one row to update!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (this.tblQueries.getSelectedRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String key = txtKey.getText().trim();
        String query = txtQuery.getText().trim().replaceAll("\\s+", " ");
        if(key.isBlank() || query.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please fill all!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!key.matches("\\w+")) {
            JOptionPane.showMessageDialog(this, "Key must be contain only letters, numbers and underscore!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirmResult = JOptionPane.showConfirmDialog(this, "Are you sure to update this query?", "Warning", JOptionPane.YES_NO_OPTION);
        if (confirmResult == JOptionPane.YES_OPTION) {
            try {
                Config.setQueries(new HashMap<String, String>() {{
                    put(key, query);
                }});
                this.tblQueries.setValueAt(query, this.tblQueries.getSelectedRow(), 1);
                resetForm();
                JOptionPane.showMessageDialog(this, "Query updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error while updating query!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdateQueryActionPerformed

    private void btnDeleteQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteQueryActionPerformed
        int[] selectedRows = tblQueries.getSelectedRows();
        if (selectedRows.length < 1) {
            JOptionPane.showMessageDialog(this, "Please select row to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to delete selected rows?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                HashMap<String, String> deleteListQueries = new HashMap<String, String>();
                for (int i = selectedRows.length - 1; i >= 0; i--) {
                    String key = this.tblQueries.getValueAt(selectedRows[i], 0).toString();
                    String query = this.tblQueries.getValueAt(selectedRows[i], 1).toString();
                    deleteListQueries.put(key, query);
                }

                Config.removeQueries(deleteListQueries);

                DefaultTableModel model = (DefaultTableModel) this.tblQueries.getModel();

                for (int i = selectedRows.length - 1; i >= 0; i--) {
                    model.removeRow(selectedRows[i]);
                }

                resetForm();

                JOptionPane.showMessageDialog(this, "Deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error while deleting query!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteQueryActionPerformed

    private void btnClearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTextActionPerformed
        resetForm();
    }//GEN-LAST:event_btnClearTextActionPerformed

    private void loadQueries() throws IOException {
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) this.tblQueries.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        DefaultTableModel queriesModel = (DefaultTableModel) this.tblQueries.getModel();
        queriesModel.setRowCount(0);

        for (Map.Entry<Object, Object> entry : Config.getQueries().entrySet()) {
            String key = entry.getKey().toString();
            String query = Config.getQueries().getProperty(key).toString();
            queriesModel.addRow(new Object[]{key, query});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueriesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueriesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueriesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueriesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QueriesDialog dialog = new QueriesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddQuery;
    private javax.swing.JButton btnClearText;
    private javax.swing.JButton btnDeleteQuery;
    private javax.swing.JButton btnUpdateQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblQueries;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextArea txtQuery;
    // End of variables declaration//GEN-END:variables
}
